A Vanilla LSTM is an LSTM model that has a single hidden layer of LSTM units, and an output layer used to make a prediction.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [44]:
df1=[10,15,14,13,16,18,16,20,25,19]

In [45]:
len(df1)

10

We can divide the sequence into multiple input/output patterns called samples, where three time steps are used as input and one time step is used as output for the one-step prediction that is being learned.

In [46]:
def split_sequence(sequence,steps):
    x,y=list(),list()
    for i in range(len(sequence)):
        end_ix=i+steps
        if end_ix>len(sequence)-1:
            break
        seq_x,seq_y=sequence[i:end_ix],sequence[end_ix]
        x.append(seq_x)
        y.append(seq_y)
    return np.array(x),np.array(y)
            
    
    

In [47]:
steps=3

x,y=split_sequence(df1,steps)


In [57]:
for i in range(len(x)):
    print(x[i],y[i])

[10 15 14] 13
[15 14 13] 16
[14 13 16] 18
[13 16 18] 16
[16 18 16] 20
[18 16 20] 25
[16 20 25] 19


In [60]:
#intializing libraries
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
 
#n_features
n_features= 1
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [63]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
x=x.reshape((x.shape[0],x.shape[1],n_features))

In [65]:
x.shape

(7, 3, 1)

In [79]:
#fitmodel
model.fit(x,y,epochs=150,verbose=0)

In [80]:
x_in=np.array([20,25,19])
x_in=x_in.reshape((1,steps,n_features))
model.predict(x_in)

array([[23.65003]], dtype=float32)